#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and your project before committing'
cd web/

echo "Running Prettier..."
npx prettier --check . ||
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

echo "Running ESLint..."
npx eslint . --ext ts --ext tsx --ext js . ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

echo "Running TypeScript compilation..."
npx tsc --pretty --noEmit ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
