#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

cd web/

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '✅✅✅✅ I have pushed successfully now. ✅✅✅✅'
